### ISSUE TITLE
Please add support for the Thread protocol

### ISSUE THREAD

**Issue by gpshead** [LIFX/lifx-protocol-docs#16]
It aims to be an open industry standard IPv6 based secure IoT protocol.  (Somewhat related to issue #6)
http://threadgroup.org/

**Comment by dotMorten** [comment]
I'm guessing the better approach is to write an AllJoyn bridge around Thread (and considering the players who are working on Thread that'll happen). It's much easier to have new protocols (and there's always a new protocol coming out), wrapped in an AllJoyn Device Bridge, than it is to add the latest greatest protocol to existing devices. For instance here's my AllJoyn Device Bridge for Philips Hue: https://github.com/dotMorten/AllJoynPhilipsHueDSB

It actually works so well the LIFX Windows app can now control my Philips Hue bulbs.

**Comment by gpshead** [comment]
My point is more that the existing protocol is not secure. It assumes that anyone on the same LAN is trusted. That is not a good assumption. Thread is a suggested basis for a new one.

Allowed controllers of things on the LAN need to be authenticated and communication between thing (bulb) and controllers needs to be encrypted and authenticated as the assumption that the LAN is secure is, while convenient and what many/most things do today, fundamentally not true.

I'm asking for this from a long term viability perspective. An external device operating as a hub to speak the existing insecure protocol is insufficient. Any device on a network needs to support an open but secure local protocol directly, not depend on the network being secure or on an actual internet connection and cloud service.

Protocol translation hubs are clearly going to _exist_ in a connected thing world as I expect many thing manufacturers to die or lose interest in old product support long before the thing's 20 year life time is up, but they should not be the first answer.

**Comment by lopter** [comment]
@gpshead has anyone thought of security via network isolation?

Running a separate, locked down, WiFi network and/or VLAN makes so much more sense to me since it allows you:
- to secure one component (the piece of software that sits in-between the networks);
- not trust manufacturers who will fail to implement a secure protocol correctly at any layer;
- withstand the time and lack of maintenance by the same manufacturers, as you pointed out.

**Comment by gpshead** [comment]
No consumer is ever going to do that. No consumer routers make that easy or
the default. Virtually all things rely on being on the same network if not
the same subnet today.

(I'm not saying it isn't a good idea. It just isn't easy and is outside of
any thing's ability to control.)

**Comment by lopter** [comment]
@gpshead why is Google working on products like OnHub then? Isn't (one of) the point(s) to have consumer routers that are being managed by competent people?

Consumer routers are just another IoT device and should be managed the same way?

**Comment by smarthall** [comment]
We are constantly reviewing and evaluating new protocols. I know Thread is one of the ones that we have considered, and will continue to watch intently. Thanks for your feedback, as we do need to know what protocols our customers are looking at too.

Regardless I don't think that this is the best place for this discussion. Maybe you'd like to start a thread in our [Developer Zone](https://community.lifx.com/) instead?
