### ISSUE TITLE
Clarification on reserved fields

### ISSUE THREAD

**Issue by eminence** [LIFX/lifx-protocol-docs#17]
Hello!

There are a lot of reserved fields in the message header, and all of these fields are documented as "must be set to zero".  However, in practice I very often see that my bulbs are sending packets with non-zero reserved fields.  

So I am thinking that when a field is documented as "reserved, must be zero" this actually means that when I (as a 3rd-party developer) construct message packets, I must set all reserved fields to zero, but 1st-party apps/bulbs might be using the reserved fields for undocumented purposes.

Is this right?

Thanks

**Comment by smarthall** [comment]
Yes that is correct, when constructing packets you must set the reserved fields to zero. You should also ignore any values you receive in these fields.

**Comment by eminence** [comment]
Thanks for the clarification!
