### ISSUE TITLE
Groups?

### ISSUE THREAD

**Issue by pdf** [LIFX/lifx-protocol-docs#7]
How do we get/set group information in this version of the protocol?

**Comment by smarthall** [comment]
Documenting the group information is on my list of things to do next.

**Comment by smarthall** [comment]
I've committed the initial documentation for groups, more detail is available [on the forums](https://community.lifx.com/t/lan-protocol-group-support/253/9?u=daniel_hall).

**Comment by pdf** [comment]
Thanks Daniel

**Comment by pdf** [comment]
Looks like we have the `Get` operations, do you plan to document `Set` operations as well?
